// This file is auto-generated by scripts/generate-payload-collections.mjs
import { AdminsCollection as Collection0 } from './features/auth/data/datasources/payload/admins.collection.ts'
import { CourseReviewsCollection as Collection1 } from './features/courses/data/datasources/payload/course-reviews.collection.ts'
import { CoursesCollection as Collection2 } from './features/courses/data/datasources/payload/courses.collection.ts'
import { EnrollmentsCollection as Collection3 } from './features/enrollments/data/datasources/payload/enrollments.collection.ts'
import { MediaCollection as Collection4 } from './features/media/data/datasources/payload/media.collection.ts'

export const featureCollections = [Collection0, Collection1, Collection2, Collection3, Collection4]
